youbrush_theme_bundle_theme_list:
    path: /theme/list
    defaults: { _controller: YouBrushThemeBundle:Theme:themeList }

youbrush_theme_bundle_constructor_item:
    path: /theme/constructor/{themeId}
    defaults: { _controller: YouBrushThemeBundle:Constructor:item }

youbrush_theme_bundle_constructor_load_components:
    path: /theme/constructor/{themeId}/api/load-components/
    defaults: { _controller: YouBrushThemeBundle:Constructor:loadThemeComponents }
