services:
    youbrush_theme_bundle.constructor_manager:
        class: YouBrush\Bundle\ThemeBundle\Constructor\ConstructorManager

    youbrush_theme_bundle.component.gallery:
        class: YouBrush\Bundle\ThemeBundle\Constructor\Component\GalleryComponent\GalleryProcessor
        tags:
            - { name: 'youbrush_theme_bundle.components', type: 'gallery' }
