services:
    youbrush_theme_bundle.constructor_manager:
        class: YouBrush\Bundle\ThemeBundle\Constructor\ConstructorManager
        arguments:
            - '@doctrine.orm.default_entity_manager'

    youbrush_theme_bundle.component.gallery:
        class: YouBrush\Bundle\ThemeBundle\Constructor\Component\GalleryComponent\GalleryComponent
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@youbrush_theme_bundle.repository.component'
            - '@security.token_storage'
            - '@jms_serializer'
            - '@form.factory'
            - '@templating'
            - '@youbrush_theme_bundle.repository.component_gallery'
        tags:
            - { name: 'youbrush_theme_bundle.components', type: 'gallery' }
