security:

    encoders:
        YouBrush\Bundle\CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        users:
            entity: { class: YouBrushCoreBundle:User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: users
            security: true
            form_login:
                check_path: /login_check
                login_path: /login
                username_parameter: authorization[email]
                password_parameter: authorization[password]
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: logout
            security: true
            anonymous: true

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
